# Generated by Django 2.2.7 on 2024-09-30 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191122_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='available',
        ),
        migrations.RemoveField(
            model_name='host',
            name='current_meeting_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='visitor_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('BUSINESS', 'Business')], default='GENERAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.Host'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='visitor_phone',
            field=models.CharField(max_length=15),
        ),
    ]
