# Generated by Django 2.2.7 on 2024-10-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20240930_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='available',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='host',
            name='current_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_host', to='accounts.Meeting'),
        ),
    ]
