# Generated by Django 2.2.7 on 2024-10-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20241002_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
