# Generated by Django 2.2.7 on 2024-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20241002_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
    ]
