# Generated by Django 2.2.7 on 2024-10-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_meeting_meeting_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='queue_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed')], default='waiting', max_length=10),
        ),
    ]
