# Generated by Django 4.2.16 on 2024-10-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20241009_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
