# Generated by Django 4.2.16 on 2024-10-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_meeting_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='checked_out',
        ),
    ]
